/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.68
 * Generated at: 2021-07-01 06:17:29 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class addmovie_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<link href=\"images/svg/moreco_favicon.gif\" rel=\"shortcut icon\" type=\"image/x-icon\">\r\n");
      out.write("<title>Moreco : 영화 등록</title>\r\n");
      out.write("<link href=\"css/add.css\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css\" rel=\"stylesheet\" integrity=\"sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x\" crossorigin=\"anonymous\">\r\n");
      out.write("<script src=\"js/jquery-3.6.0.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("    function inp_check() {\r\n");
      out.write("    	\r\n");
      out.write("    	if (document.forms[1].category_idx.value == 0) {\r\n");
      out.write("    		alert(\"장르를 선택하세요\");\r\n");
      out.write("    		return false;\r\n");
      out.write("    	}\r\n");
      out.write("        if (document.forms[1].movie_name.value == \"\") {\r\n");
      out.write("            alert(\"영화명을 작성하세요\");\r\n");
      out.write("            document.forms[1].movie_name.focus();\r\n");
      out.write("            return false;\r\n");
      out.write("        }\r\n");
      out.write("        if (document.forms[1].movie_director.value == \"\") {\r\n");
      out.write("            alert(\"감독명을 작성하세요\");\r\n");
      out.write("            document.forms[1].movie_director.focus();\r\n");
      out.write("            return false;\r\n");
      out.write("        }\r\n");
      out.write("        if (document.forms[1].movie_rank.value == \"\") {\r\n");
      out.write("            alert(\"등급을 작성하세요\");\r\n");
      out.write("            document.forms[1].movie_rank.focus();\r\n");
      out.write("            return false;\r\n");
      out.write("        }\r\n");
      out.write("        else {\r\n");
      out.write("        	var movie_rank_check = document.forms[1].movie_rank.value.substring(0,2);\r\n");
      out.write("        	if (movie_rank_check != '전체' && movie_rank_check != '12' && movie_rank_check != '15' && movie_rank_check != '18') {\r\n");
      out.write("        		alert(\"등급을 확인하세요\");\r\n");
      out.write("                document.forms[1].movie_rank.focus();\r\n");
      out.write("                return false;\r\n");
      out.write("        	}\r\n");
      out.write("        	else {\r\n");
      out.write("        		document.forms[1].real_movie_rank.value = movie_rank_check;\r\n");
      out.write("        	}\r\n");
      out.write("        }\r\n");
      out.write("        if (document.forms[1].movie_content.value == \"\") {\r\n");
      out.write("            alert(\"줄거리를 작성하세요\");\r\n");
      out.write("            document.forms[1].movie_content.focus();\r\n");
      out.write("            return false;\r\n");
      out.write("        }\r\n");
      out.write("        if (document.forms[1].movie_img.value == \"\") {\r\n");
      out.write("            alert(\"이미지를 등록하세요\");\r\n");
      out.write("            document.forms[1].movie_img.focus();\r\n");
      out.write("            return false;\r\n");
      out.write("        }\r\n");
      out.write("        var fileVal = $(\"#inputGroupFile01\").val(); \r\n");
      out.write("        fileVal = fileVal.slice(fileVal.indexOf(\".\")+1).toLowerCase(); \r\n");
      out.write("        \r\n");
      out.write("        \r\n");
      out.write("        if(fileVal != \"jpg\" && fileVal != \"png\" && fileVal != \"jpeg\" && fileVal != \"gif\" && fileVal != \"bmp\"){ \r\n");
      out.write("    		alert(\"이미지 파일만 가능합니다\");\r\n");
      out.write("    		return false;\r\n");
      out.write("        } \r\n");
      out.write("        \r\n");
      out.write("    	var maxSize = 10 * 1024 * 1024;\r\n");
      out.write("    	var fileSize = 0;\r\n");
      out.write("    	var browser = navigator.appName;\r\n");
      out.write("    	\r\n");
      out.write("    	if (browser == \"Microsoft Internet Explorer\") {\r\n");
      out.write("    		var oas = new ActiveXObject(\"Scripting.FileSystemObject\");\r\n");
      out.write("    		fileSize = oas.getFile( file.value ).size;\r\n");
      out.write("    	}\r\n");
      out.write("    	else {\r\n");
      out.write("    		fileSize = file.files[0].size;\r\n");
      out.write("    	}\r\n");
      out.write("    	if(fileSize > maxSize) {\r\n");
      out.write("            alert(\"10MB 이하인 이미지만 등록 가능합니다\");\r\n");
      out.write("            return false;\r\n");
      out.write("        }\r\n");
      out.write("    }\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<nav id=\"top\">\r\n");
      out.write("		");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "header.jsp", out, true);
      out.write("\r\n");
      out.write("	</nav>\r\n");
      out.write("	<div id=\"wrap\">\r\n");
      out.write("		<aside>\r\n");
      out.write("			");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "sidebar.jsp", out, true);
      out.write("\r\n");
      out.write("		</aside>\r\n");
      out.write("		<section>\r\n");
      out.write("			<h2>영화 등록</h2>\r\n");
      out.write("    		<div class=\"add_movies\">\r\n");
      out.write("        		<form method=\"post\" action=\"addmoviePro.jsp\" enctype=\"multipart/form-data\" onsubmit=\"return inp_check();\" >\r\n");
      out.write("        		    <select class=\"form-select form-select-lg mb-3\" name=\"category_idx\" aria-label=\".form-select-lg example\" style=\"width:559px; height:58px; font-size:16px;\">\r\n");
      out.write("  						<option selected value=\"0\">장르</option>\r\n");
      out.write("  						<option value=\"1\">액션</option>\r\n");
      out.write("  						<option value=\"2\">코미디</option>\r\n");
      out.write("  						<option value=\"3\">드라마</option>\r\n");
      out.write("  						<option value=\"4\">멜로</option>\r\n");
      out.write("  						<option value=\"5\">공포</option>\r\n");
      out.write("  						<option value=\"6\">SF/판타지</option>\r\n");
      out.write("  						<option value=\"7\">애니메이션</option>\r\n");
      out.write("					</select>\r\n");
      out.write("            		<div class=\"form-floating mb-3\">\r\n");
      out.write("                		<input type=\"text\" class=\"form-control\" name=\"movie_name\" id=\"floatingInput\" style=\"width:559px;\" placeholder=\"영화명\">\r\n");
      out.write("                		<label for=\"floatingInput\">영화명</label>\r\n");
      out.write("            		</div>\r\n");
      out.write("            		<div class=\"form-floating mb-3\">\r\n");
      out.write("                		<input type=\"text\" class=\"form-control\" name=\"movie_director\" id=\"floatingInput\" style=\"width:559px;\" placeholder=\"감독명\">\r\n");
      out.write("                		<label for=\"floatingInput\">감독명</label>\r\n");
      out.write("            		</div>\r\n");
      out.write("            		<div class=\"form-floating mb-3\">\r\n");
      out.write("                		<input type=\"text\" class=\"form-control\" name=\"movie_rank\" id=\"floatingInput\" style=\"width:259px;\" placeholder=\"등급\">\r\n");
      out.write("                		<label for=\"floatingInput\">등급</label>\r\n");
      out.write("                		<input type=\"hidden\" name=\"real_movie_rank\"/>\r\n");
      out.write("            		</div>\r\n");
      out.write("            		<div class=\"form-floating\">\r\n");
      out.write("                		<textarea class=\"form-control\" name=\"movie_content\" placeholder=\"Leave a comment here\" id=\"floatingTextarea2\" style=\"width:659px; height: 200px;\"></textarea>\r\n");
      out.write("                		<label for=\"floatingTextarea2\">줄거리</label>\r\n");
      out.write("            		</div>\r\n");
      out.write("            		<br>\r\n");
      out.write("            		<div class=\"input-group mb-3\" style=\"width:659px;\">\r\n");
      out.write("                		<input type=\"file\" accept=\"image/*\" name=\"movie_img\" class=\"form-control\" id=\"inputGroupFile01\" >\r\n");
      out.write("            		</div>\r\n");
      out.write("            		<div class=\"add_btn\">\r\n");
      out.write("            			<button type=\"submit\" class=\"btn btn-danger\">등록하기</button>\r\n");
      out.write("            		</div>\r\n");
      out.write("        		</form>\r\n");
      out.write("    		</div>\r\n");
      out.write("		</section>\r\n");
      out.write("	</div>\r\n");
      out.write("	<footer>\r\n");
      out.write("		");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "footer.html", out, true);
      out.write("\r\n");
      out.write("	</footer>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
